### PR TITLE
OZ-52: Monkey patches for SENAITE result options to support UUIDs.

### PR DESCRIPTION
**Pull request by Ruhanga**
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-52

### CODE REVIEW

**Review by mks-d — COMMENTED** [review]
@Ruhanga could we try to trim this down and remove the files that we don't use?

**Review by Ruhanga — COMMENTED** [review]
Yes indeed @mks-d. I'll push a commit effecting this.

**Comment by Ruhanga** [comment]
Hi @mks-d, @enyachoke, could you review this PR when you've gotten some time? Thanks.

**Review by enyachoke — APPROVED** [review]
LGTM

**Review by mks-d — APPROVED** [review]

**Pull request merged**
